### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RaySheikh** [appfoundry/react-adal-authentication-session-sample#1]
Thank you so much for putting this together. This has helped me a lot! One question, where can I do a get call to my api to return some data?

Thank you again!

**Comment by CauseOfDev** [comment]
Hi RaySheikh, thank you for the kind words!

In the App.js file we've got two examples of network requests:

https://github.com/appfoundry/react-adal-authentication-session-sample/blob/82cdbce98a836bba924b289ce5236bf186aa8a33/src/App.js#L8-L12

and

https://github.com/appfoundry/react-adal-authentication-session-sample/blob/82cdbce98a836bba924b289ce5236bf186aa8a33/src/App.js#L24-L30

There are other ways for doing network requests, such as with a state manager(like redux) and a framework for side effects (like saga/mobx), but I would forward you to their respective documentation for that.

I hope this helps you with your question!
